"""add_user_encrypted_password

Revision ID: 1d1bfcd0c525
Revises: 2ca8f897a11b
Create Date: 2026-06-20 20:24:01.769789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1bfcd0c525'
down_revision: Union[str, None] = '2ca8f897a11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_password')
    # ### end Alembic commands ###
