"""add max_user_id to users

Revision ID: 20c03dd50d88
Revises: de5751a56d4f
Create Date: 2026-06-24 18:29:30.714920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c03dd50d88'
down_revision: Union[str, None] = 'de5751a56d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_user_id')
    # ### end Alembic commands ###
