"""add_notification_link_and_chat_tables

Revision ID: 24f2e6dc40e8
Revises: ffac7d99c383
Create Date: 2026-06-20 13:09:50.672960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f2e6dc40e8'
down_revision: Union[str, None] = 'ffac7d99c383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_chat_participant')
    )
    op.create_index(op.f('ix_chat_participants_id'), 'chat_participants', ['id'], unique=False)
    op.add_column('notifications', sa.Column('link', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # Миграция существующих групп: создаём для каждой группы чат и добавляем участников
    op.execute("""
        INSERT INTO chat_rooms (name, type, group_id, created_by_id, created_at)
        SELECT 'Чат: ' || g.name, 'group', g.id, COALESCE(g.teacher_id, 1), NOW()
        FROM groups g
        WHERE NOT EXISTS (SELECT 1 FROM chat_rooms cr WHERE cr.group_id = g.id);
    """)
    op.execute("""
        INSERT INTO chat_participants (room_id, user_id, role, joined_at)
        SELECT cr.id, g.teacher_id, 'admin', NOW()
        FROM groups g
        JOIN chat_rooms cr ON cr.group_id = g.id
        WHERE g.teacher_id IS NOT NULL
        ON CONFLICT (room_id, user_id) DO NOTHING;
    """)
    op.execute("""
        INSERT INTO chat_participants (room_id, user_id, role, joined_at)
        SELECT cr.id, u.id, 'member', NOW()
        FROM users u
        JOIN groups g ON g.id = u.group_id
        JOIN chat_rooms cr ON cr.group_id = g.id
        ON CONFLICT (room_id, user_id) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_deleted')
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'entity_type')
    op.drop_column('notifications', 'link')
    op.drop_index(op.f('ix_chat_participants_id'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
