"""add_academy_fields

Revision ID: 2ca8f897a11b
Revises: 24f2e6dc40e8
Create Date: 2026-06-20 18:14:05.205303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca8f897a11b'
down_revision: Union[str, None] = '24f2e6dc40e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('yandex_disk_public_key', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    op.add_column('enrollments', sa.Column('assigned_by_id', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'users', ['assigned_by_id'], ['id'])
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'assigned_at')
    op.drop_column('enrollments', 'assigned_by_id')
    op.drop_column('courses', 'last_sync_at')
    op.drop_column('courses', 'yandex_disk_public_key')
    # ### end Alembic commands ###
