"""add_hr_fields_and_leaves_kpis

Revision ID: 635a2481c0f7
Revises: cfd5bcecb879
Create Date: 2026-06-23 21:26:30.319300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635a2481c0f7'
down_revision: Union[str, None] = 'cfd5bcecb879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('actual', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_kpis_id'), 'staff_kpis', ['id'], unique=False)
    op.create_table('staff_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_leaves_id'), 'staff_leaves', ['id'], unique=False)
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employment_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('salary_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('salary_rate', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hr_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('contract_number', sa.String(), nullable=True))
    op.execute("UPDATE users SET salary_type = 'hourly' WHERE salary_type IS NULL")
    op.execute("UPDATE users SET salary_rate = 0 WHERE salary_rate IS NULL")
    op.execute("UPDATE users SET hr_status = 'active' WHERE hr_status IS NULL")
    op.alter_column('users', 'salary_type', existing_type=sa.String(), nullable=False)
    op.alter_column('users', 'salary_rate', existing_type=sa.Integer(), nullable=False)
    op.alter_column('users', 'hr_status', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contract_number')
    op.drop_column('users', 'hr_status')
    op.drop_column('users', 'salary_rate')
    op.drop_column('users', 'salary_type')
    op.drop_column('users', 'employment_date')
    op.drop_column('users', 'position')
    op.drop_index(op.f('ix_staff_leaves_id'), table_name='staff_leaves')
    op.drop_table('staff_leaves')
    op.drop_index(op.f('ix_staff_kpis_id'), table_name='staff_kpis')
    op.drop_table('staff_kpis')
    # ### end Alembic commands ###
