"""add system_settings

Revision ID: 6ac060bb18bb
Revises: 8383f7b88ef0
Create Date: 2026-06-23 23:00:28.297292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac060bb18bb'
down_revision: Union[str, None] = '8383f7b88ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('school_legal_name', sa.String(), nullable=True),
    sa.Column('school_address', sa.Text(), nullable=True),
    sa.Column('school_phone', sa.String(), nullable=True),
    sa.Column('school_email', sa.String(), nullable=True),
    sa.Column('school_website', sa.String(), nullable=True),
    sa.Column('school_logo_url', sa.String(), nullable=True),
    sa.Column('school_timezone', sa.String(), nullable=False),
    sa.Column('school_currency', sa.String(), nullable=False),
    sa.Column('platform_default_language', sa.String(), nullable=False),
    sa.Column('platform_registration_enabled', sa.Boolean(), nullable=False),
    sa.Column('platform_maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('platform_max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(), nullable=True),
    sa.Column('smtp_password', sa.String(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_sender_name', sa.String(), nullable=True),
    sa.Column('smtp_sender_email', sa.String(), nullable=True),
    sa.Column('sms_provider', sa.String(), nullable=True),
    sa.Column('sms_api_key', sa.String(), nullable=True),
    sa.Column('sms_sender_name', sa.String(), nullable=True),
    sa.Column('telegram_bot_token', sa.String(), nullable=True),
    sa.Column('telegram_channel_id', sa.String(), nullable=True),
    sa.Column('telegram_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('yandex_client_id', sa.String(), nullable=True),
    sa.Column('yandex_client_secret', sa.String(), nullable=True),
    sa.Column('yandex_redirect_uri', sa.String(), nullable=True),
    sa.Column('yandex_disk_enabled', sa.Boolean(), nullable=False),
    sa.Column('yandex_calendar_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
