"""add_homework_title_description_and_cascade_deletes

Revision ID: 848f320276d2
Revises: d4facd73125c
Create Date: 2026-06-21 21:18:06.733893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848f320276d2'
down_revision: Union[str, None] = 'd4facd73125c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('title', sa.String(), nullable=True))
    op.add_column('homeworks', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'description')
    op.drop_column('homeworks', 'title')
    # ### end Alembic commands ###
