"""extend_organization_and_branch_for_school_settings

Revision ID: aad11ac69da4
Revises: a2b1a68605f0
Create Date: 2026-06-23 17:47:51.760460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad11ac69da4'
down_revision: Union[str, None] = 'a2b1a68605f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('square_logo_url', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('wide_logo_url', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('certificate_bg_url', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('card_bg_url', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('direction', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('main_phone', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'city')
    op.drop_column('organizations', 'main_phone')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'direction')
    op.drop_column('organizations', 'license_number')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'card_bg_url')
    op.drop_column('organizations', 'certificate_bg_url')
    op.drop_column('organizations', 'wide_logo_url')
    op.drop_column('organizations', 'square_logo_url')
    op.drop_column('organizations', 'short_name')
    # ### end Alembic commands ###
