"""add tinkoff fields to orders

Revision ID: cb2bf4597759
Revises: f6d65d5f57f3
Create Date: 2026-06-25 03:17:28.901938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2bf4597759'
down_revision: Union[str, None] = 'f6d65d5f57f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tinkoff_payment_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_url', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'payment_url')
    op.drop_column('orders', 'tinkoff_payment_id')
    # ### end Alembic commands ###
