"""add yandex disk fields to lesson_contents

Revision ID: d4facd73125c
Revises: 1d1bfcd0c525
Create Date: 2026-06-21 18:13:54.926163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4facd73125c'
down_revision: Union[str, None] = '1d1bfcd0c525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_contents', sa.Column('yandex_disk_path', sa.String(), nullable=True))
    op.add_column('lesson_contents', sa.Column('yandex_disk_md5', sa.String(), nullable=True))
    op.add_column('lesson_contents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lesson_contents_yandex_disk_path'), 'lesson_contents', ['yandex_disk_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_contents_yandex_disk_path'), table_name='lesson_contents')
    op.drop_column('lesson_contents', 'file_size')
    op.drop_column('lesson_contents', 'yandex_disk_md5')
    op.drop_column('lesson_contents', 'yandex_disk_path')
    # ### end Alembic commands ###
