"""add_group_status

Revision ID: d8a7c3e24acb
Revises: e66284152667
Create Date: 2026-06-23 16:28:42.697712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a7c3e24acb'
down_revision: Union[str, None] = 'e66284152667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('status', sa.String(), nullable=False, server_default='current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'status')
    # ### end Alembic commands ###
