"""add schedule_reminder_logs

Revision ID: de5751a56d4f
Revises: baaeed2374f2
Create Date: 2026-06-24 00:54:38.718807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.migration_helpers import table_exists, index_exists


# revision identifiers, used by Alembic.
revision: str = 'de5751a56d4f'
down_revision: Union[str, None] = 'baaeed2374f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if not table_exists('schedule_reminder_logs'):
        op.create_table('schedule_reminder_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('schedule_id', sa.Integer(), nullable=False),
        sa.Column('occurrence_date', sa.Date(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reminder_type', sa.String(), nullable=False),
        sa.Column('channel', sa.String(), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('schedule_id', 'occurrence_date', 'user_id', 'reminder_type', name='uq_schedule_reminder_log')
        )
    if not index_exists('schedule_reminder_logs', 'ix_schedule_reminder_logs_id'):
        op.create_index(op.f('ix_schedule_reminder_logs_id'), 'schedule_reminder_logs', ['id'], unique=False)
    if not index_exists('schedule_reminder_logs', 'ix_schedule_reminder_logs_schedule_id'):
        op.create_index(op.f('ix_schedule_reminder_logs_schedule_id'), 'schedule_reminder_logs', ['schedule_id'], unique=False)
    if not index_exists('schedule_reminder_logs', 'ix_schedule_reminder_logs_user_id'):
        op.create_index(op.f('ix_schedule_reminder_logs_user_id'), 'schedule_reminder_logs', ['user_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_reminder_logs_user_id'), table_name='schedule_reminder_logs')
    op.drop_index(op.f('ix_schedule_reminder_logs_schedule_id'), table_name='schedule_reminder_logs')
    op.drop_index(op.f('ix_schedule_reminder_logs_id'), table_name='schedule_reminder_logs')
    op.drop_table('schedule_reminder_logs')
    # ### end Alembic commands ###
