"""add knowledge_articles table

Revision ID: e66284152667
Revises: a5dad66b1ed5
Create Date: 2026-06-22 10:05:18.314446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66284152667'
down_revision: Union[str, None] = 'a5dad66b1ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_course_id_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'courses', ['course_id'], ['id'])
    op.drop_constraint('lesson_progress_lesson_id_fkey', 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_progress', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint('schedules_course_id_fkey', 'schedules', type_='foreignkey')
    op.drop_constraint('schedules_lesson_id_fkey', 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key('schedules_lesson_id_fkey', 'schedules', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('schedules_course_id_fkey', 'schedules', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'lesson_progress', type_='foreignkey')
    op.create_foreign_key('lesson_progress_lesson_id_fkey', 'lesson_progress', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_course_id_fkey', 'groups', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
