"""extend_group_and_add_memberships

Revision ID: f5cc51e1610f
Revises: ccda521901bf
Create Date: 2026-06-23 19:32:05.790979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cc51e1610f'
down_revision: Union[str, None] = 'ccda521901bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('individual_hourly_rate', sa.Integer(), nullable=True),
    sa.Column('individual_lesson_count', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('individual_monthly_fee', sa.Integer(), nullable=True),
    sa.Column('auto_invoices_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_id'), 'group_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_group_memberships_student_id'), 'group_memberships', ['student_id'], unique=False)

    # Новые поля сначала nullable, чтобы не ломать существующие группы
    op.add_column('groups', sa.Column('room', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('study_type', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('language', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('level', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('groups', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('groups', sa.Column('academic_hour_minutes', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('balance_type', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('hourly_rate', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('monthly_fee', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('auto_invoices_enabled', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('certificates_enabled', sa.Boolean(), nullable=True))

    # Заполняем дефолты для существующих групп
    op.execute("UPDATE groups SET study_type = 'mini_group', academic_hour_minutes = 45, balance_type = 'lessons', hourly_rate = 0, auto_invoices_enabled = true, certificates_enabled = false")

    # Теперь делаем обязательными
    op.alter_column('groups', 'study_type', nullable=False)
    op.alter_column('groups', 'academic_hour_minutes', nullable=False)
    op.alter_column('groups', 'balance_type', nullable=False)
    op.alter_column('groups', 'hourly_rate', nullable=False)
    op.alter_column('groups', 'auto_invoices_enabled', nullable=False)
    op.alter_column('groups', 'certificates_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'certificates_enabled')
    op.drop_column('groups', 'auto_invoices_enabled')
    op.drop_column('groups', 'monthly_fee')
    op.drop_column('groups', 'hourly_rate')
    op.drop_column('groups', 'balance_type')
    op.drop_column('groups', 'academic_hour_minutes')
    op.drop_column('groups', 'end_date')
    op.drop_column('groups', 'start_date')
    op.drop_column('groups', 'level')
    op.drop_column('groups', 'language')
    op.drop_column('groups', 'study_type')
    op.drop_column('groups', 'room')
    op.drop_index(op.f('ix_group_memberships_student_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    # ### end Alembic commands ###
